# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
name: Create Release
run-name: Creating draft release for ${{ github.ref_name }}

on:
  push:
    tags:
      - 'release-*'

jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image Tool installer
        run: |
          mvn -version
          mvn -B clean package
      - id: version
        run: echo "::set-output name=number::`echo "${{ github.ref_name }}" | sed 's/release-//'`"
      - name: Create draft release and attach installer zip
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
          --draft \
          --generate-notes \
          --title 'WebLogic Image Tool ${{ steps.version.outputs.number }}' \
          installer/target/imagetool.zip
